language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t joshkardos/docker-build -f Dockerfile.dev .

script:
  - docker run -e CI=true joshkardos/docker-build npm run test
